### ISSUE TITLE
refresh getTotalNumberOfCheckboxes if changes in task

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#437]
If theres a change in a task, a new checkbox gets a new hash and the total number for checkboxes will then be wrong. Because it doesn't remove the "old" one

**Comment by Skagevang** [comment]
Found another bug. If I check something and leave refresh the page. The checkboxes are false.

**Comment by NorwegianKiwi** [comment]
The last part is being fixed with #613 .

An idea to how to partly solve the first issue, is to mark any completed lessons as "completed", e.g. "astrokatt: completed". Then, when updating state from localstorage (or perhaps just updating checkboxes from state), if a lesson is marked as "completed", just mark all checkboxes as "true" immediately. Then it won't matter if some of the checkboxes change later.

For the lessons that are not complete, there will be changes, but I guess that is ok.

I also suggest to only "fix" the checkbox-state when entering a lesson.

**Comment by NorwegianKiwi** [comment]
The suggestion above has been made into a separate issue: #615
