### ISSUE TITLE
Wrong logo if equal amount of lessons

### ISSUE THREAD

**Issue by Skagevang** [kodeklubben/codeclub-viewer#623]
Now it gives this error in the console:
```
Warning: Prop `src` did not match. Server: "/_/oppgaver/src/learntomod/logo-black.8bdf4e.png" Client: "/_/oppgaver/src/arduino/logo-black.db64bb.png"
```
Also check the website and look at arduino

**Comment by NorwegianKiwi** [comment]
The problem is that the course items are sorted only on lesson count. If the lesson count is equal for two courses, the sorting within them is arbitrary. It turns out that the server sorts them differently than the client, and therefore the mismatch.

The fix would be to make sure the sorting is consistent always, e.g. by sorting alphabetically within the courses that have equal amount of lessons.
